# Generated by Django 5.0.7 on 2024-08-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='secret_key',
            field=models.CharField(default='', max_length=32),
        ),
    ]
