# Generated by Django 5.0.7 on 2024-08-14 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discountPercentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=6)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='userId',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='6b8c9c9468d145df8d507cd0037c6662', max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='otp',
            field=models.IntegerField(default=-111111),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField()),
                ('reviewerName', models.CharField(max_length=256)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.product')),
            ],
        ),
    ]
