# Generated by Django 5.0.7 on 2024-08-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_userverification_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_id',
            field=models.CharField(default='45a5d0d9e2b94a0f8187ab59c77f2c5c', max_length=24),
        ),
    ]
