# Generated by Django 5.0.7 on 2024-07-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_login_signup_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
