# Generated by Django 5.0.7 on 2024-08-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_product_remove_otpverification_userid_alter_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='da08d1a2860c4dabba2af24495312433', max_length=24, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
