# Generated by Django 5.0.7 on 2024-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='38cfd662bfbf48d2b8fff7485fde1c63', max_length=24, primary_key=True, serialize=False),
        ),
    ]
