# Generated by Django 5.0.7 on 2024-08-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='5d053fb68087476a838d2c6ea36e826e', max_length=24, primary_key=True, serialize=False),
        ),
    ]
