# Generated by Django 5.0.7 on 2024-08-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='f841709df8d5415999dbdc682a946ec6', max_length=24, primary_key=True, serialize=False),
        ),
    ]
