# Generated by Django 5.0.7 on 2024-08-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='d5bd4a42601b4cf0a8b4d53de0bee3cb', max_length=24, primary_key=True, serialize=False),
        ),
    ]
