# Generated by Django 5.0.7 on 2024-08-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0010_alter_user_groups_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='7a5d3018ed0d45da89a2e93bc00150a9', max_length=24, primary_key=True, serialize=False),
        ),
    ]
