# Generated by Django 5.0.7 on 2024-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='cd35096f93784dafab015036ae9a15b6', max_length=24, primary_key=True, serialize=False),
        ),
    ]
