# Generated by Django 5.0.7 on 2024-08-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0012_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='79c3cf378e73450192bbca734b4dc706', max_length=24, primary_key=True, serialize=False),
        ),
    ]
