# Generated by Django 5.0.7 on 2024-08-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0013_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='f4686e7c62544f868c88a2f9b57bb8fc', max_length=24, primary_key=True, serialize=False),
        ),
    ]
