# Generated by Django 5.0.7 on 2024-08-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0014_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='d82c100cf8c84a3baaa30c967ceb4849', max_length=24, primary_key=True, serialize=False),
        ),
    ]
